insert into M_COUNTRY values ('352','ISL','IS',1,'アイスランド','Iceland','北ヨーロッパ');
insert into M_COUNTRY values ('372','IRL','IE',2,'アイルランド','Ireland','西ヨーロッパ');
insert into M_COUNTRY values ('031','AZE','AZ',3,'アゼルバイジャン','Azerbaijan','東ヨーロッパ');
insert into M_COUNTRY values ('004','AFG','AF',4,'アフガニスタン','Afghanistan','中東');
insert into M_COUNTRY values ('840','USA','US',5,'アメリカ合衆国','United States','北アメリカ');
insert into M_COUNTRY values ('850','VIR','VI',6,'アメリカ領ヴァージン諸島','Virgin Islands, U.S.','中央アメリカ');
insert into M_COUNTRY values ('016','ASM','AS',7,'アメリカ領サモア','American Samoa','オセアニア');
insert into M_COUNTRY values ('784','ARE','AE',8,'アラブ首長国連邦','United Arab Emirates','中東');
insert into M_COUNTRY values ('012','DZA','DZ',9,'アルジェリア','Algeria','北アフリカ');
insert into M_COUNTRY values ('032','ARG','AR',10,'アルゼンチン','Argentina','南アメリカ');
insert into M_COUNTRY values ('533','ABW','AW',11,'アルバ','Aruba','中央アメリカ');
insert into M_COUNTRY values ('008','ALB','AL',12,'アルバニア','Albania','東ヨーロッパ');
insert into M_COUNTRY values ('051','ARM','AM',13,'アルメニア','Armenia','東ヨーロッパ');
insert into M_COUNTRY values ('660','AIA','AI',14,'アンギラ','Anguilla','中央アメリカ');
insert into M_COUNTRY values ('024','AGO','AO',15,'アンゴラ','Angola','南アフリカ');
insert into M_COUNTRY values ('028','ATG','AG',16,'アンティグア・バーブーダ','Antigua and Barbuda','中央アメリカ');
insert into M_COUNTRY values ('020','AND','AD',17,'アンドラ','Andorra','西ヨーロッパ');
insert into M_COUNTRY values ('887','YEM','YE',18,'イエメン','Yemen','中東');
insert into M_COUNTRY values ('826','GBR','GB',19,'イギリス','United Kingdom','西ヨーロッパ');
insert into M_COUNTRY values ('086','IOT','IO',20,'イギリス領インド洋地域','British Indian Ocean Territory','インド洋地域');
insert into M_COUNTRY values ('092','VGB','VG',21,'イギリス領ヴァージン諸島','Virgin Islands, British','中央アメリカ');
insert into M_COUNTRY values ('376','ISR','IL',22,'イスラエル','Israel','中東');
insert into M_COUNTRY values ('380','ITA','IT',23,'イタリア','Italy','西ヨーロッパ');
insert into M_COUNTRY values ('368','IRQ','IQ',24,'イラク','Iraq','中東');
insert into M_COUNTRY values ('364','IRN','IR',25,'イラン','Iran, Islamic Republic of','中東');
insert into M_COUNTRY values ('356','IND','IN',26,'インド','India','南アジア');
insert into M_COUNTRY values ('360','IDN','ID',27,'インドネシア','Indonesia','東南アジア');
insert into M_COUNTRY values ('876','WLF','WF',28,'ウォリス・フツナ','Wallis and Futuna','オセアニア');
insert into M_COUNTRY values ('800','UGA','UG',29,'ウガンダ','Uganda','中央アフリカ');
insert into M_COUNTRY values ('804','UKR','UA',30,'ウクライナ','Ukraine','東ヨーロッパ');
insert into M_COUNTRY values ('860','UZB','UZ',31,'ウズベキスタン','Uzbekistan','中央アジア');
insert into M_COUNTRY values ('858','URY','UY',32,'ウルグアイ','Uruguay','南アメリカ');
insert into M_COUNTRY values ('218','ECU','EC',33,'エクアドル','Ecuador','南アメリカ');
insert into M_COUNTRY values ('818','EGY','EG',34,'エジプト','Egypt','北アフリカ');
insert into M_COUNTRY values ('233','EST','EE',35,'エストニア','Estonia','東ヨーロッパ');
insert into M_COUNTRY values ('231','ETH','ET',36,'エチオピア','Ethiopia','東アフリカ');
insert into M_COUNTRY values ('232','ERI','ER',37,'エリトリア','Eritrea','東アフリカ');
insert into M_COUNTRY values ('222','SLV','SV',38,'エルサルバドル','El Salvador','中央アメリカ');
insert into M_COUNTRY values ('036','AUS','AU',39,'オーストラリア','Australia','オセアニア');
insert into M_COUNTRY values ('040','AUT','AT',40,'オーストリア','Austria','東ヨーロッパ');
insert into M_COUNTRY values ('248','ALA','AX',41,'オーランド諸島','Aland Islands','北ヨーロッパ');
insert into M_COUNTRY values ('512','OMN','OM',42,'オマーン','Oman','中東');
insert into M_COUNTRY values ('528','NLD','NL',43,'オランダ','Netherlands','西ヨーロッパ');
insert into M_COUNTRY values ('288','GHA','GH',44,'ガーナ','Ghana','西アフリカ');
insert into M_COUNTRY values ('132','CPV','CV',45,'カーボベルデ','Cape Verde','西アフリカ');
insert into M_COUNTRY values ('831','GGY','GG',46,'ガーンジー','Guernsey','西ヨーロッパ');
insert into M_COUNTRY values ('328','GUY','GY',47,'ガイアナ','Guyana','南アメリカ');
insert into M_COUNTRY values ('398','KAZ','KZ',48,'カザフスタン','Kazakhstan','中央アジア');
insert into M_COUNTRY values ('634','QAT','QA',49,'カタール','Qatar','中東');
insert into M_COUNTRY values ('581','UMI','UM',50,'合衆国領有小離島','United States Minor Outlying Islands','オセアニア');
insert into M_COUNTRY values ('124','CAN','CA',51,'カナダ','Canada','北アメリカ');
insert into M_COUNTRY values ('266','GAB','GA',52,'ガボン','Gabon','中央アフリカ');
insert into M_COUNTRY values ('120','CMR','CM',53,'カメルーン','Cameroon','中央アフリカ');
insert into M_COUNTRY values ('270','GMB','GM',54,'ガンビア','Gambia','西アフリカ');
insert into M_COUNTRY values ('116','KHM','KH',55,'カンボジア','Cambodia','東南アジア');
insert into M_COUNTRY values ('580','MNP','MP',56,'北マリアナ諸島','Northern Mariana Islands','オセアニア');
insert into M_COUNTRY values ('324','GIN','GN',57,'ギニア','Guinea','西アフリカ');
insert into M_COUNTRY values ('624','GNB','GW',58,'ギニアビサウ','Guinea-Bissau','西アフリカ');
insert into M_COUNTRY values ('196','CYP','CY',59,'キプロス','Cyprus','地中海地域');
insert into M_COUNTRY values ('192','CUB','CU',60,'キューバ','Cuba','中央アメリカ');
insert into M_COUNTRY values ('531','CUW','CW',61,'キュラソー島','Curacao','中央アメリカ');
insert into M_COUNTRY values ('300','GRC','GR',62,'ギリシャ','Greece','西ヨーロッパ');
insert into M_COUNTRY values ('296','KIR','KI',63,'キリバス','Kiribati','オセアニア');
insert into M_COUNTRY values ('417','KGZ','KG',64,'キルギス','Kyrgyzstan','中央アジア');
insert into M_COUNTRY values ('320','GTM','GT',65,'グアテマラ','Guatemala','中央アメリカ');
insert into M_COUNTRY values ('312','GLP','GP',66,'グアドループ','Guadeloupe','中央アメリカ');
insert into M_COUNTRY values ('316','GUM','GU',67,'グアム','Guam','オセアニア');
insert into M_COUNTRY values ('414','KWT','KW',68,'クウェート','Kuwait','中東');
insert into M_COUNTRY values ('184','COK','CK',69,'クック諸島','Cook Islands','オセアニア');
insert into M_COUNTRY values ('304','GRL','GL',70,'グリーンランド','Greenland','北ヨーロッパ');
insert into M_COUNTRY values ('162','CXR','CX',71,'クリスマス島 (オーストラリア)','Christmas Island','オセアニア');
insert into M_COUNTRY values ('268','GEO','GE',72,'グルジア','Georgia','東ヨーロッパ');
insert into M_COUNTRY values ('308','GRD','GD',73,'グレナダ','Grenada','中央アメリカ');
insert into M_COUNTRY values ('191','HRV','HR',74,'クロアチア','Croatia','東ヨーロッパ');
insert into M_COUNTRY values ('136','CYM','KY',75,'ケイマン諸島','Cayman Islands','中央アメリカ');
insert into M_COUNTRY values ('404','KEN','KE',76,'ケニア','Kenya','東アフリカ');
insert into M_COUNTRY values ('166','CCK','CC',78,'ココス諸島','Cocos (Keeling) Islands','インド洋地域');
insert into M_COUNTRY values ('188','CRI','CR',79,'コスタリカ','Costa Rica','中央アメリカ');
insert into M_COUNTRY values ('174','COM','KM',80,'コモロ','Comoros','インド洋地域');
insert into M_COUNTRY values ('170','COL','CO',81,'コロンビア','Colombia','南アメリカ');
insert into M_COUNTRY values ('178','COG','CG',82,'コンゴ共和国','Congo','中央アフリカ');
insert into M_COUNTRY values ('180','COD','CD',83,'コンゴ民主共和国','Congo, the Democratic Republic of the','中央アフリカ');
insert into M_COUNTRY values ('682','SAU','SA',84,'サウジアラビア','Saudi Arabia','中東');
insert into M_COUNTRY values ('239','SGS','GS',85,'サウスジョージア・サウスサンドウィッチ諸島','South Georgia and the South Sandwich Islands','南アメリカ');
insert into M_COUNTRY values ('882','WSM','WS',86,'サモア','Samoa','オセアニア');
insert into M_COUNTRY values ('678','STP','ST',87,'サントメ・プリンシペ','Sao Tome and Principe','中央アフリカ');
insert into M_COUNTRY values ('652','BLM','BL',88,'サン・バルテルミー島','Saint Barthelemy','中央アメリカ');
insert into M_COUNTRY values ('894','ZMB','ZM',89,'ザンビア','Zambia','南アフリカ');
insert into M_COUNTRY values ('666','SPM','PM',90,'サンピエール島・ミクロン島','Saint Pierre and Miquelon','北アメリカ');
insert into M_COUNTRY values ('674','SMR','SM',91,'サンマリノ','San Marino','西ヨーロッパ');
insert into M_COUNTRY values ('663','MAF','MF',92,'サン・マルタン (西インド諸島)','Saint Martin (French part)','中央アメリカ');
insert into M_COUNTRY values ('694','SLE','SL',93,'シエラレオネ','Sierra Leone','西アフリカ');
insert into M_COUNTRY values ('262','DJI','DJ',94,'ジブチ','Djibouti','東アフリカ');
insert into M_COUNTRY values ('292','GIB','GI',95,'ジブラルタル','Gibraltar','西ヨーロッパ');
insert into M_COUNTRY values ('832','JEY','JE',96,'ジャージー','Jersey','西ヨーロッパ');
insert into M_COUNTRY values ('388','JAM','JM',97,'ジャマイカ','Jamaica','中央アメリカ');
insert into M_COUNTRY values ('760','SYR','SY',98,'シリア|シリア・アラブ共和国','Syrian Arab Republic','中東');
insert into M_COUNTRY values ('702','SGP','SG',99,'シンガポール','Singapore','東南アジア');
insert into M_COUNTRY values ('534','SXM','SX',100,'シント・マールテン','Sint Maarten (Dutch part)','中央アメリカ');
insert into M_COUNTRY values ('716','ZWE','ZW',101,'ジンバブエ','Zimbabwe','南アフリカ');
insert into M_COUNTRY values ('756','CHE','CH',102,'スイス','Switzerland','西ヨーロッパ');
insert into M_COUNTRY values ('752','SWE','SE',103,'スウェーデン','Sweden','北ヨーロッパ');
insert into M_COUNTRY values ('729','SDN','SD',104,'スーダン','Sudan','東アフリカ');
insert into M_COUNTRY values ('744','SJM','SJ',105,'スヴァールバル諸島およびヤンマイエン島','Svalbard and Jan Mayen','北ヨーロッパ');
insert into M_COUNTRY values ('724','ESP','ES',106,'スペイン','Spain','西ヨーロッパ');
insert into M_COUNTRY values ('740','SUR','SR',107,'スリナム','Suriname','南アメリカ');
insert into M_COUNTRY values ('144','LKA','LK',108,'スリランカ','Sri Lanka','南アジア');
insert into M_COUNTRY values ('703','SVK','SK',109,'スロバキア','Slovakia','東ヨーロッパ');
insert into M_COUNTRY values ('705','SVN','SI',110,'スロベニア','Slovenia','東ヨーロッパ');
insert into M_COUNTRY values ('748','SWZ','SZ',111,'スワジランド','Swaziland','南アフリカ');
insert into M_COUNTRY values ('690','SYC','SC',112,'セーシェル','Seychelles','インド洋地域');
insert into M_COUNTRY values ('226','GNQ','GQ',113,'赤道ギニア','Equatorial Guinea','中央アフリカ');
insert into M_COUNTRY values ('686','SEN','SN',114,'セネガル','Senegal','西アフリカ');
insert into M_COUNTRY values ('688','SRB','RS',115,'セルビア','Serbia','東ヨーロッパ');
insert into M_COUNTRY values ('659','KNA','KN',116,'セントクリストファー・ネイビス','Saint Kitts and Nevis','中央アメリカ');
insert into M_COUNTRY values ('670','VCT','VC',117,'セントビンセントおよびグレナディーン諸島','Saint Vincent and the Grenadines','中央アメリカ');
insert into M_COUNTRY values ('654','SHN','SH',118,'セントヘレナ・アセンションおよびトリスタンダクーニャ','Saint Helena, Ascension and Tristan da Cunha','西アフリカ');
insert into M_COUNTRY values ('662','LCA','LC',119,'セントルシア','Saint Lucia','中央アメリカ');
insert into M_COUNTRY values ('706','SOM','SO',120,'ソマリア','Somalia','東アフリカ');
insert into M_COUNTRY values ('090','SLB','SB',121,'ソロモン諸島','Solomon Islands','オセアニア');
insert into M_COUNTRY values ('796','TCA','TC',122,'タークス・カイコス諸島','Turks and Caicos Islands','中央アメリカ');
insert into M_COUNTRY values ('764','THA','TH',123,'タイ王国|タイ','Thailand','東南アジア');
insert into M_COUNTRY values ('410','KOR','KR',124,'大韓民国','Korea, Republic of','東アジア');
insert into M_COUNTRY values ('158','TWN','TW',125,'台湾','Taiwan, Province of China','東アジア');
insert into M_COUNTRY values ('762','TJK','TJ',126,'タジキスタン','Tajikistan','中央アジア');
insert into M_COUNTRY values ('834','TZA','TZ',127,'タンザニア','Tanzania, United Republic of','東アフリカ');
insert into M_COUNTRY values ('203','CZE','CZ',128,'チェコ','Czech Republic','東ヨーロッパ');
insert into M_COUNTRY values ('148','TCD','TD',129,'チャド','Chad','中央アフリカ');
insert into M_COUNTRY values ('140','CAF','CF',130,'中央アフリカ共和国','Central African Republic','中央アフリカ');
insert into M_COUNTRY values ('156','CHN','CN',131,'中華人民共和国','China','東アジア');
insert into M_COUNTRY values ('788','TUN','TN',132,'チュニジア','Tunisia','北アフリカ');
insert into M_COUNTRY values ('152','CHL','CL',134,'チリ','Chile','南アメリカ');
insert into M_COUNTRY values ('798','TUV','TV',135,'ツバル','Tuvalu','オセアニア');
insert into M_COUNTRY values ('208','DNK','DK',136,'デンマーク','Denmark','北ヨーロッパ');
insert into M_COUNTRY values ('276','DEU','DE',137,'ドイツ','Germany','西ヨーロッパ');
insert into M_COUNTRY values ('768','TGO','TG',138,'トーゴ','Togo','西アフリカ');
insert into M_COUNTRY values ('772','TKL','TK',139,'トケラウ','Tokelau','オセアニア');
insert into M_COUNTRY values ('214','DOM','DO',140,'ドミニカ共和国','Dominican Republic','中央アメリカ');
insert into M_COUNTRY values ('212','DMA','DM',141,'ドミニカ国','Dominica','中央アメリカ');
insert into M_COUNTRY values ('780','TTO','TT',142,'トリニダード・トバゴ','Trinidad and Tobago','中央アメリカ');
insert into M_COUNTRY values ('795','TKM','TM',143,'トルクメニスタン','Turkmenistan','中央アジア');
insert into M_COUNTRY values ('792','TUR','TR',144,'トルコ','Turkey','中東');
insert into M_COUNTRY values ('776','TON','TO',145,'トンガ','Tonga','オセアニア');
insert into M_COUNTRY values ('566','NGA','NG',146,'ナイジェリア','Nigeria','中央アフリカ');
insert into M_COUNTRY values ('520','NRU','NR',147,'ナウル','Nauru','オセアニア');
insert into M_COUNTRY values ('516','NAM','NA',148,'ナミビア','Namibia','南アフリカ');
insert into M_COUNTRY values ('010','ATA','AQ',149,'南極','Antarctica','南極');
insert into M_COUNTRY values ('570','NIU','NU',150,'ニウエ','Niue','オセアニア');
insert into M_COUNTRY values ('558','NIC','NI',151,'ニカラグア','Nicaragua','中央アメリカ');
insert into M_COUNTRY values ('562','NER','NE',152,'ニジェール','Niger','中央アフリカ');
insert into M_COUNTRY values ('392','JPN','JP',153,'日本','Japan','東アジア');
insert into M_COUNTRY values ('732','ESH','EH',154,'西サハラ','Western Sahara','西アフリカ');
insert into M_COUNTRY values ('540','NCL','NC',155,'ニューカレドニア','New Caledonia','オセアニア');
insert into M_COUNTRY values ('554','NZL','NZ',156,'ニュージーランド','New Zealand','オセアニア');
insert into M_COUNTRY values ('524','NPL','NP',157,'ネパール','Nepal','南アジア');
insert into M_COUNTRY values ('574','NFK','NF',158,'ノーフォーク島','Norfolk Island','オセアニア');
insert into M_COUNTRY values ('578','NOR','NO',159,'ノルウェー','Norway','北ヨーロッパ');
insert into M_COUNTRY values ('334','HMD','HM',160,'ハード島とマクドナルド諸島','Heard Island and McDonald Islands','インド洋地域');
insert into M_COUNTRY values ('048','BHR','BH',161,'バーレーン','Bahrain','中東');
insert into M_COUNTRY values ('332','HTI','HT',162,'ハイチ','Haiti','中央アメリカ');
insert into M_COUNTRY values ('586','PAK','PK',163,'パキスタン','Pakistan','南アジア');
insert into M_COUNTRY values ('336','VAT','VA',164,'バチカン市国','Holy See (Vatican City State)','西ヨーロッパ');
insert into M_COUNTRY values ('591','PAN','PA',165,'パナマ','Panama','中央アメリカ');
insert into M_COUNTRY values ('548','VUT','VU',166,'バヌアツ','Vanuatu','オセアニア');
insert into M_COUNTRY values ('044','BHS','BS',167,'バハマ','Bahamas','中央アメリカ');
insert into M_COUNTRY values ('598','PNG','PG',168,'パプアニューギニア','Papua New Guinea','オセアニア');
insert into M_COUNTRY values ('060','BMU','BM',169,'バミューダ諸島','Bermuda','中央アメリカ');
insert into M_COUNTRY values ('585','PLW','PW',170,'パラオ','Palau','オセアニア');
insert into M_COUNTRY values ('600','PRY','PY',171,'パラグアイ','Paraguay','南アメリカ');
insert into M_COUNTRY values ('052','BRB','BB',172,'バルバドス','Barbados','中央アメリカ');
insert into M_COUNTRY values ('275','PSE','PS',173,'パレスチナ','Palestinian Territory, Occupied','中東');
insert into M_COUNTRY values ('348','HUN','HU',174,'ハンガリー','Hungary','東ヨーロッパ');
insert into M_COUNTRY values ('050','BGD','BD',175,'バングラデシュ','Bangladesh','南アジア');
insert into M_COUNTRY values ('626','TLS','TL',176,'東ティモール','Timor-Leste','東南アジア');
insert into M_COUNTRY values ('612','PCN','PN',177,'ピトケアン諸島','Pitcairn','オセアニア');
insert into M_COUNTRY values ('242','FJI','FJ',178,'フィジー','Fiji','オセアニア');
insert into M_COUNTRY values ('608','PHL','PH',179,'フィリピン','Philippines','東南アジア');
insert into M_COUNTRY values ('246','FIN','FI',180,'フィンランド','Finland','北ヨーロッパ');
insert into M_COUNTRY values ('064','BTN','BT',181,'ブータン','Bhutan','南アジア');
insert into M_COUNTRY values ('074','BVT','BV',182,'ブーベ島','Bouvet Island','南極');
insert into M_COUNTRY values ('630','PRI','PR',183,'プエルトリコ','Puerto Rico','中央アメリカ');
insert into M_COUNTRY values ('234','FRO','FO',184,'フェロー諸島','Faroe Islands','北ヨーロッパ');
insert into M_COUNTRY values ('238','FLK','FK',185,'フォークランド諸島','Falkland Islands (Malvinas)','南アメリカ');
insert into M_COUNTRY values ('076','BRA','BR',186,'ブラジル','Brazil','南アメリカ');
insert into M_COUNTRY values ('250','FRA','FR',187,'フランス','France','西ヨーロッパ');
insert into M_COUNTRY values ('254','GUF','GF',188,'フランス領ギアナ','French Guiana','南アメリカ');
insert into M_COUNTRY values ('258','PYF','PF',189,'フランス領ポリネシア','French Polynesia','オセアニア');
insert into M_COUNTRY values ('260','ATF','TF',190,'フランス領南方・南極地域','French Southern Territories','インド洋地域');
insert into M_COUNTRY values ('100','BGR','BG',191,'ブルガリア','Bulgaria','東ヨーロッパ');
insert into M_COUNTRY values ('854','BFA','BF',192,'ブルキナファソ','Burkina Faso','西アフリカ');
insert into M_COUNTRY values ('096','BRN','BN',193,'ブルネイ','Brunei Darussalam','東南アジア');
insert into M_COUNTRY values ('108','BDI','BI',194,'ブルンジ','Burundi','中央アフリカ');
insert into M_COUNTRY values ('704','VNM','VN',195,'ベトナム','Viet Nam','東南アジア');
insert into M_COUNTRY values ('204','BEN','BJ',196,'ベナン','Benin','西アフリカ');
insert into M_COUNTRY values ('862','VEN','VE',197,'ベネズエラ','Venezuela, Bolivarian Republic of','南アメリカ');
insert into M_COUNTRY values ('112','BLR','BY',198,'ベラルーシ','Belarus','東ヨーロッパ');
insert into M_COUNTRY values ('084','BLZ','BZ',199,'ベリーズ','Belize','中央アメリカ');
insert into M_COUNTRY values ('604','PER','PE',200,'ペルー','Peru','南アメリカ');
insert into M_COUNTRY values ('056','BEL','BE',201,'ベルギー','Belgium','西ヨーロッパ');
insert into M_COUNTRY values ('616','POL','PL',202,'ポーランド','Poland','東ヨーロッパ');
insert into M_COUNTRY values ('070','BIH','BA',203,'ボスニア・ヘルツェゴビナ','Bosnia and Herzegovina','東ヨーロッパ');
insert into M_COUNTRY values ('072','BWA','BW',204,'ボツワナ','Botswana','南アフリカ');
insert into M_COUNTRY values ('535','BES','BQ',205,'ボネール、シント・ユースタティウスおよびサバ','Bonaire, Saint Eustatius and Saba','中央アメリカ');
insert into M_COUNTRY values ('068','BOL','BO',206,'ボリビア','Bolivia, Plurinational State of','南アメリカ');
insert into M_COUNTRY values ('620','PRT','PT',207,'ポルトガル','Portugal','西ヨーロッパ');
insert into M_COUNTRY values ('344','HKG','HK',208,'香港','Hong Kong','東アジア');
insert into M_COUNTRY values ('340','HND','HN',209,'ホンジュラス','Honduras','中央アメリカ');
insert into M_COUNTRY values ('584','MHL','MH',210,'マーシャル諸島','Marshall Islands','オセアニア');
insert into M_COUNTRY values ('446','MAC','MO',211,'マカオ','Macao','東アジア');
insert into M_COUNTRY values ('807','MKD','MK',212,'マケドニア共和国','Macedonia, the former Yugoslav Republic of','東ヨーロッパ');
insert into M_COUNTRY values ('450','MDG','MG',213,'マダガスカル','Madagascar','インド洋地域');
insert into M_COUNTRY values ('175','MYT','YT',214,'マヨット','Mayotte','インド洋地域');
insert into M_COUNTRY values ('454','MWI','MW',215,'マラウイ','Malawi','南アフリカ');
insert into M_COUNTRY values ('466','MLI','ML',216,'マリ共和国|マリ','Mali','西アフリカ');
insert into M_COUNTRY values ('470','MLT','MT',217,'マルタ','Malta','地中海地域');
insert into M_COUNTRY values ('474','MTQ','MQ',218,'マルティニーク','Martinique','中央アメリカ');
insert into M_COUNTRY values ('458','MYS','MY',219,'マレーシア','Malaysia','東南アジア');
insert into M_COUNTRY values ('833','IMN','IM',220,'マン島','Isle of Man','西ヨーロッパ');
insert into M_COUNTRY values ('583','FSM','FM',221,'ミクロネシア連邦','Micronesia, Federated States of','オセアニア');
insert into M_COUNTRY values ('710','ZAF','ZA',222,'南アフリカ共和国','South Africa','南アフリカ');
insert into M_COUNTRY values ('728','SSD','SS',223,'南スーダン','South Sudan','東アフリカ');
insert into M_COUNTRY values ('104','MMR','MM',224,'ミャンマー','Myanmar','東南アジア');
insert into M_COUNTRY values ('484','MEX','MX',225,'メキシコ','Mexico','中央アメリカ');
insert into M_COUNTRY values ('480','MUS','MU',226,'モーリシャス','Mauritius','南アフリカ');
insert into M_COUNTRY values ('478','MRT','MR',227,'モーリタニア','Mauritania','西アフリカ');
insert into M_COUNTRY values ('508','MOZ','MZ',228,'モザンビーク','Mozambique','南アフリカ');
insert into M_COUNTRY values ('492','MCO','MC',229,'モナコ','Monaco','西ヨーロッパ');
insert into M_COUNTRY values ('462','MDV','MV',230,'モルディブ','Maldives','インド洋地域');
insert into M_COUNTRY values ('498','MDA','MD',231,'モルドバ','Moldova, Republic of','東ヨーロッパ');
insert into M_COUNTRY values ('504','MAR','MA',232,'モロッコ','Morocco','北アフリカ');
insert into M_COUNTRY values ('496','MNG','MN',233,'モンゴル国','Mongolia','東アジア');
insert into M_COUNTRY values ('499','MNE','ME',234,'モンテネグロ','Montenegro','東ヨーロッパ');
insert into M_COUNTRY values ('500','MSR','MS',235,'モントセラト','Montserrat','中央アメリカ');
insert into M_COUNTRY values ('400','JOR','JO',236,'ヨルダン','Jordan','中東');
insert into M_COUNTRY values ('428','LVA','LV',238,'ラトビア','Latvia','東ヨーロッパ');
insert into M_COUNTRY values ('440','LTU','LT',239,'リトアニア','Lithuania','東ヨーロッパ');
insert into M_COUNTRY values ('434','LBY','LY',240,'リビア','Libya','北アフリカ');
insert into M_COUNTRY values ('438','LIE','LI',241,'リヒテンシュタイン','Liechtenstein','西ヨーロッパ');
insert into M_COUNTRY values ('430','LBR','LR',242,'リベリア','Liberia','西アフリカ');
insert into M_COUNTRY values ('642','ROU','RO',243,'ルーマニア','Romania','東ヨーロッパ');
insert into M_COUNTRY values ('442','LUX','LU',244,'ルクセンブルク','Luxembourg','西ヨーロッパ');
insert into M_COUNTRY values ('646','RWA','RW',245,'ルワンダ','Rwanda','中央アフリカ');
insert into M_COUNTRY values ('426','LSO','LS',246,'レソト','Lesotho','南アフリカ');
insert into M_COUNTRY values ('422','LBN','LB',247,'レバノン','Lebanon','中東');
insert into M_COUNTRY values ('638','REU','RE',248,'レユニオン','Reunion','インド洋地域');
insert into M_COUNTRY values ('643','RUS','RU',249,'ロシア連邦','Russian Federation','ロシア');
insert into M_COUNTRY values ('384','CIV','CI',77,'コートジボワール',"Cote d'Ivoire",'西アフリカ');
insert into M_COUNTRY values ('418','LAO','LA',237,'ラオス',"Lao People's Democratic Republic",'東南アジア');
insert into M_COUNTRY values ('408','PRK','KP',133,'朝鮮民主主義人民共和国',"Korea, Democratic People's Republic of",'東アジア');
